version: "3.7"
services:
  db: # in production replace db service with real database and models with reflection
    image: mysql
    container_name: db_app
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=startupsupport
    ports:
      - "5400:8000"
    expose:
      - "8000"

  redis:
    image: redis:alpine
    container_name: redis_app
    restart: always
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    volumes:
      - grafanadata:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    environment:
      - ENV_FILE=.env.prod
    depends_on:
      - "db"
    ports:
      - 8000:8000
volumes:
  grafanadata:
  prometheusdata:
