"""fix FormFields relationship

Revision ID: 2e38b98f6fe3
Revises: 723c2e47c880
Create Date: 2024-03-30 14:52:10.141231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e38b98f6fe3'
down_revision: Union[str, None] = '723c2e47c880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
