"""fk projectdata to formfields

Revision ID: 723c2e47c880
Revises: b0fddd75df25
Create Date: 2024-03-29 18:45:17.765372

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "723c2e47c880"
down_revision: Union[str, None] = "b0fddd75df25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_data", sa.Column("form_fields_id_form_fields", sa.Integer(), nullable=False))
    op.create_index("fk_form_fields_id_form_fields1_idx", "project_data", ["form_fields_id_form_fields"], unique=False)
    op.create_foreign_key(
        "fk_form_fields_id_form_fields1",
        "project_data",
        "form_fields",
        ["form_fields_id_form_fields"],
        ["id_form_fields"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_form_fields_id_form_fields1", "project_data", type_="foreignkey")
    op.drop_index("fk_form_fields_id_form_fields1_idx", table_name="project_data")
    op.drop_column("project_data", "form_fields_id_form_fields")
    # ### end Alembic commands ###
