"""requirements column

Revision ID: 86058d29f193
Revises: b0fddd75df25
Create Date: 2024-03-29 18:12:58.068965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86058d29f193'
down_revision: Union[str, None] = 'b0fddd75df25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supports', sa.Column('requirements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supports', 'requirements')
    # ### end Alembic commands ###
